#!/usr/bin/env bash
#information about the domain

print_d () {
	x=$(dig "$1" | grep -A1 'ANSWER SECTION:' | tr '\t' ' ' | cut -d ' ' -f 4- | tail -1)	
	echo "$2 $x" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 2 ]
then
    print_d "$2.$1" "$2"
else
    print_d "www.$1" "www"
    print_d "lb-01.$1" "lb-01"
    print_d "web-01.$1" "web-01"
    print_d "web-02.$1" "web-02"
fi
