#!/usr/bin/env bash
#install load balancer

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update
apt-get -y install haproxy

cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 211037-web-01 3.85.136.6:80 check
    server 211037-web-02 18.209.152.171:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
