#!/usr/bin/env bash
#back up of a server
#day=$(date +"%d")
#month=$(date +"%m")
#year=$(date +"%Y")
mysqldump --all-databases --user=root --password="$1" > backup.sql
file="$(date + "%d")-$(date + "%m")-$(date + "%Y").tar.gz"
tar -czvf "$file" backup.sql
