#!/usr/bin/env bash
#advanced task
function term()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}
function sint()
{
	echo "Y U no love me?!"
	rm /var/run/myscript.pid
	exit
}
trap term SIGTERM
trap sint SIGINT
echo $$ >> /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
done
